[build-system]
requires = [
    "setuptools",
    "prompt_toolkit",
    "comberload",
    "pyoload",
]
build-backend = "setuptools.build_meta"

[project]
name = "shellsy"
version = "v1.0.0a1.dev1"
authors = "ken-morel"
classifiers = []↑
dependencies

description

dynamic

entry-points

gui-scripts

keywords

license

maintainers

name

optional-dependencies

readme

requires-python

scripts

urls

versiontt5tttttttttttgg
